coverage:
  range: 90...100
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 5%

comment:
  layout: header, reach, sunburst, diff, flags, files, footer
