name: Generate Installers

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Specify Release Tag'
        default: 'Example: v1.2.3-alpha'
        required: true
      branch:
        description: 'Specify Branch'
        required: true
        default: 'staging'

permissions:
  contents: write

jobs:
  build_installer_windows:
    name: Build Windows Installer
    uses: ./.github/workflows/build-installer-windows.yml
    with:
      branch: ${{ inputs.branch }}
  build_installer_mac:
    name: Build macOS Installer
    uses: ./.github/workflows/build-installer-mac.yml
    with:
      branch: ${{ inputs.branch }}
  upload_to_release_page:
    name: Upload To Release Page
    needs: [ build_installer_windows, build_installer_mac ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Installers
        uses: actions/download-artifact@v3
        id: download
      - name: Zip Installer Directories
        run: |
          zip -r Windows-Installer.zip Windows-Installer
          zip -r macOS-Installer.zip macOS-Installer
      - name: Upload Windows Installer
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ inputs.release_tag }}
          files: |
            Windows-Installer.zip
            macOS-Installer.zip
