name: Build Installers

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to Build Installers From"
        default: "main"
        required: true
        type: string

jobs:
  build_installer_windows:
    name: Build Windows Installer
    uses: ./.github/workflows/build-installer-windows.yml
    with:
      branch: ${{ inputs.branch }}
  build_installer_mac:
    name: Build macOS Installer
    uses: ./.github/workflows/build-installer-mac.yml
    with:
      branch: ${{ inputs.branch }}
  build_installer_linux:
    name: Build Linux Installer
    uses: ./.github/workflows/build-installer-linux.yml
    with:
      branch: ${{ inputs.branch }}
