name: Build Windows Installer

on:
  workflow_call:
    inputs:
      branch:
        description: 'Specify Branch'
        required: true
        default: 'staging'
        type: string
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specify Branch'
        required: true
        default: 'staging'

jobs:
  build_installer:
    name: Build Installer
    runs-on: windows-latest
    steps:
      - name: Download WiX
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip
      - name: Decompress WiX
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix
      - name: Add WiX to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ github.token }}
      - name: Install Custom Maven Dependencies
        run: mvn validate
      - name: Generate Installer
        run: mvn -B clean:clean compiler:compile javafx:jlink jpackage:jpackage@win
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Installer
          path: target/dist/*.exe
