name: Generate Installers

on:
  release:
    types: [published]
  workflow_call:
  workflow_dispatch:

jobs:
  build_installer_windows:
    name: Build Windows Installer
    uses: ./.github/workflows/build-installer-windows.yml

#  # Todo: disabled due to lack of Apple signing key.
#  build_installer_mac:
#    name: Build macOS Installer
#    uses: ./.github/workflows/build-installer-windows.yml
