name: Build macOS Installer

on:
  workflow_call:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build_installer:
    name: Build Installer
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ github.token }}
      - name: Install Custom Maven Dependencies
        run: mvn validate
        # Todo: get Apple signing key
      - name: Generate Installer
        run: mvn -B clean:clean compiler:compile javafx:jlink jpackage:jpackage@mac
      - name: Upload macOS Installer
        uses: actions/upload-artifact@v3
        with:
          name: macOS-Installer
          path: target/dist/*.dmg
