name: Build Windows Installer

on:
  workflow_call:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build_installer:
    runs-on: windows-latest

    steps:
      - name: Download WiX
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip
      - name: Decompress WiX
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix
      - name: Add WiX to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn -B clean:clean compiler:compile javafx:jlink jpackage:jpackage@win
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Installer
          path: target/dist/*.exe
