name: Build And Upload Installers

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Specify Release Tag"
        default: "Example: v1.2.3"
        required: true

permissions:
  contents: write

jobs:
  # Run Final Tests
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yml
    with:
      upload_to_codecov: "NO"

  # Build Installers
  build_installer_windows:
    name: Build Windows Installer
    needs: [ run_tests ]
    uses: ./.github/workflows/build-installer-windows.yml
    with:
      branch: "staging"
  build_installer_mac:
    name: Build macOS Installer
    needs: [ run_tests ]
    uses: ./.github/workflows/build-installer-mac.yml
    with:
      branch: "staging"

  # Upload Installers
  upload_to_release_page:
    name: Upload To Release Page
    needs: [ build_installer_windows, build_installer_mac ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Installers
        uses: actions/download-artifact@v3
        id: download
      - name: Zip Installer Directories
        run: |
          zip -r Windows-Installer.zip Windows-Installer
          zip -r macOS-Installer.zip macOS-Installer
      - name: Upload Installers
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ inputs.release_tag }}
          files: |
            Windows-Installer.zip
            macOS-Installer.zip
      - name: Delete Artifacts
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: |
            Windows-Installer
            macOS-Installer
