name: Build Linux Installer

on:
  workflow_call:
    inputs:
      branch:
        description: "Specify Branch"
        required: true
        default: "staging"
        type: string

jobs:
  build_installer:
    name: Build Installer
    runs-on: ubuntu-latest
    steps:
      - name: Install Needed Dependencies
        run: sudo apt-get install -y binutils fakeroot
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ github.token }}
      - name: Install Custom Maven Dependencies
        run: mvn validate
      - name: Generate Installer
        run: mvn -B clean:clean compiler:compile javafx:jlink jpackage:jpackage@linux
      - name: Upload Linux Installer
        uses: actions/upload-artifact@v3
        with:
          name: Linux-Installer
          path: target/dist/*.deb
