name: Generate Installers

on:
  release:
    types: [published]
  workflow_call
  workflow_dispatch:
    branches: [ main ]

jobs:
  run_tests:
    uses: ./.github/workflows/reusable/run-tests.yml
  build_installer_windows:
    needs: run_tests
    uses: ./.github/workflows/reusable/build-installer-windows.yml
  build_installer_mac:
    needs: run_tests
    uses: ./.github/workflows/reusable/build-installer-windows.yml
