name: Generate Release Artifacts

on:
  push:
    branches:
      - staging

jobs:
  # Build Installers
  build_installer_windows:
    name: Build Windows Installer
    uses: ./.github/workflows/build-installer-windows.yml
    with:
      branch: "staging"
  build_installer_mac:
    name: Build macOS Installer
    uses: ./.github/workflows/build-installer-mac.yml
    with:
      branch: "staging"
  build_installer_linux:
    name: Build Linux Installer
    uses: ./.github/workflows/build-installer-linux.yml
    with:
      branch: "staging"

  # Upload artifacts
  release:
    name: Release
    needs: [ build_installer_windows, build_installer_mac, build_installer_linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          persist-credentials: false
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ secrets.SEMVER_GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"
      - name: Install Custom Maven Dependencies
        run: mvn validate
      - name: Download Installers
        uses: actions/download-artifact@v3
        id: download
      - name: Zip Installer Directories
        run: |
          zip -r Windows-Installer.zip Windows-Installer
          zip -r macOS-Installer.zip macOS-Installer
          zip -r Linux-Installer.zip Linux-Installer
      - name: Generate SHA256 Signatures
        run: |
          (sha256sum Windows-Installer.zip | cut -d " " -f1) > Windows-Installer.sha256
          (sha256sum macOS-Installer.zip | cut -d " " -f1) > macOS-Installer.sha256
          (sha256sum Linux-Installer.zip | cut -d " " -f1) > Linux-Installer.sha256
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release-Artifacts
          path: |
            Windows-Installer.zip
            Windows-Installer.sha256
            macOS-Installer.zip
            macOS-Installer.sha256
            Linux-Installer.zip
            Linux-Installer.sha256
