name: Release

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Build Installers
  build_installer_windows:
    name: Build Windows Installer
    uses: ./.github/workflows/build-installer-windows.yml
    with:
      branch: "staging"
  build_installer_mac:
    name: Build macOS Installer
    uses: ./.github/workflows/build-installer-mac.yml
    with:
      branch: "staging"

  # Release
  release:
    name: Release
    needs: [ build_installer_windows, build_installer_mac ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ github.token }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"
      - name: Download Installers
        uses: actions/download-artifact@v3
        id: download
      - name: Zip Installer Directories
        run: |
          zip -r Windows-Installer.zip Windows-Installer
          zip -r macOS-Installer.zip macOS-Installer
      - name: Setup Semantic Release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: Release To GitHub
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}