name: Run Tests On Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ github.token }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Test with Maven
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run mvn --batch-mode clean test
          elif [ "$RUNNER_OS" == "Windows" ]; then
            mvn --batch-mode clean test
          elif [ "$RUNNER_OS" == "macOS" ]; then
            mvn --batch-mode clean test
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
