name: Run Tests On Push To Main

on:
  push:
    branches: [ main ]
    paths:
      - 'src/main/java/site/overwrite/auditranscribe/**'
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    uses: ./.github/workflows/reusable/run-tests.yml
