name: Run Tests On Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - name: Test with Maven
        run: mvn --batch-mode clean test
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: target/site/jacoco/jacoco.xml
