name: Run Tests On Pull To Staging

on:
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yml
    with:
      upload_to_codecov: "YES"
      branch: "staging"
