name: Run Tests On Push

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Test with Maven on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: xvfb-run mvn --batch-mode clean test
      - name: Test with Maven on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: mvn --batch-mode clean test
      - name: Test with Maven on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: mvn --batch-mode clean test
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: target/site/jacoco/jacoco.xml
