name: Run Tests On Pull

on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yml
    with:
      upload_to_codecov: "YES"
      branch: ${{ github.ref }}