name: Run Tests

on:
  workflow_call:
    inputs:
      upload_to_codecov:
        description: "Upload to CodeCov?"
        default: "YES"
        required: true
        type: string
      branch:
        description: "Branch to test"
        default: "main"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      upload_to_codecov:
        description: "Upload to CodeCov?"
        default: "Enter either 'YES' or 'NO'"
        required: true
        type: string
      branch:
        description: "Branch to test"
        default: "main"
        required: true
        type: string

jobs:
  main_tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ github.token }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"
      - name: Test with Maven
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run mvn --batch-mode clean test
          elif [ "$RUNNER_OS" == "Windows" ]; then
            mvn --batch-mode clean test
          elif [ "$RUNNER_OS" == "macOS" ]; then
            mvn --batch-mode clean test
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
      - name: Upload Coverage Report to CodeCov
        if: ${{ inputs.upload_to_codecov == 'YES' }}
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
