name: Run Tests On Push To Main

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.java"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yml
    with:
      upload_to_codecov: "YES"
